### ISSUE TITLE
Error in `[.data.frame`(filter(df_gtf, type == "gene"), , c("seqnames",  :    undefined columns selected

### ISSUE THREAD

**Issue by Riverhuang42** [rreybeyb/MoAIMS#1]
Hi there,

I had a try with the test data you provided and I got some error code. Could you please give some suggestions?

> moaims(sample_info_file = "/Users/MoAIMS/sample_info.txt", gtf_file ="/Users/transcripts.sorted.gtf",strand_specific = 1, is_paired = F, proj_name='test')

#Get bins info.
Error in `[.data.frame`(filter(df_gtf, type == "gene"), , c("seqnames",  : 
  undefined columns selected

**Comment by rreybeyb** [comment]
> Hi there,
> 
> I had a try with the test data you provided and I got some error code. Could you please give some suggestions?
> 
> > moaims(sample_info_file = "/Users/MoAIMS/sample_info.txt", gtf_file ="/Users/transcripts.sorted.gtf",strand_specific = 1, is_paired = F, proj_name='test')
> 
> #Get bins info.
> Error in `[.data.frame`(filter(df_gtf, type == "gene"), , c("seqnames", :
> undefined columns selected

GENCODE GTF is recommended. Can you tell me the source of GTF file?

**Comment by Riverhuang42** [comment]
I used GRCm38.86.gtf

**Comment by rreybeyb** [comment]
> I used GRCm38.86.gtf. Is there anything I can do if I want to stick with my current gtf file?

I updated codes, it works now.

**Comment by Riverhuang42** [comment]
Thanks. All good now.
