### ISSUE TITLE
gtf file format

### ISSUE THREAD

**Issue by liyan910117** [rreybeyb/MoAIMS#2]
Hello, can give me the template of gtf file.
when i use the package to identify m6A peak, its return an error:
#Get bins info.
Error in if (strand == "+") { : argument is of length zero
Calls: moaims ... getBinInfo -> .getBinInfoObj -> lapply -> FUN -> .binByGene

**Comment by rreybeyb** [comment]
> Hello, can give me the template of gtf file.
> when i use the package to identify m6A peak, its return an error:
> #Get bins info.
> Error in if (strand == "+") { : argument is of length zero
> Calls: moaims ... getBinInfo -> .getBinInfoObj -> lapply -> FUN -> .binByGene

The template gtf is from GENCODE. Maybe you can check if the chromosome names are consistent between your bam files and gtf file.

**Comment by liyan910117** [comment]
thank you!

**Comment by liyan910117** [comment]
Hi, there,
I got some error code as follows. Could you please give some suggestions?

#Fit models.
Error in while (abs(logLik[iter] - logLik[iter - 1]) > eps & iter < iter_stop) { : 
  missing value where TRUE/FALSE needed
Calls: moaims -> fitEM -> em1S
