### ISSUE TITLE
Error in Fit models

### ISSUE THREAD

**Issue by liyan910117** [rreybeyb/MoAIMS#3]
Hi, there,
I got some error code as follows. Could you please give some suggestions?

#Fit models.
Error in while (abs(logLik[iter] - logLik[iter - 1]) > eps & iter < iter_stop) { :
missing value where TRUE/FALSE needed
Calls: moaims -> fitEM -> em1S

**Comment by rreybeyb** [comment]
> Hi, there,
> I got some error code as follows. Could you please give some suggestions?
> 
> #Fit models.
> Error in while (abs(logLik[iter] - logLik[iter - 1]) > eps & iter < iter_stop) { :
> missing value where TRUE/FALSE needed
> Calls: moaims -> fitEM -> em1S

Did you do mark-duplication for bam files? If you did, please try to set var_init=10 or 20.

**Comment by liyan910117** [comment]
thank you!
