### ISSUE TITLE
bed12 output: most of peaks are not in proper bed12 format

### ISSUE THREAD

**Issue by KR-Chow** [rreybeyb/MoAIMS#7]
Hi Yiqian, 

I found that the in most of peaks, the chromStart + chromStarts[last] + blockSizes[last] do not equal to chromEnd.

Could you please check it?

[test.txt](https://github.com/rreybeyb/MoAIMS/files/6469809/test.txt)

**Comment by rreybeyb** [comment]
> Hi Yiqian,
> 
> I found that the in most of peaks, the chromStart + chromStarts[last] + blockSizes[last] do not equal to chromEnd.
> 
> Could you please check it?
> 
> [test.txt](https://github.com/rreybeyb/MoAIMS/files/6469809/test.txt)

It was fixed. Thanks.
